PG_ADMIN_USERNAME=postgres
PG_ADMIN_PASSWORD=postgres
PG_ADMIN_HOST=localhost
PG_ADMIN_PORT=35432
PG_ADMIN_DATABASE=postgres

PG_RUNNER_USERNAME=sbtest
PG_RUNNER_PASSWORD=password
PG_RUNNER_HOST=localhost
PG_RUNNER_PORT=35432
PG_RUNNER_DATABASE=sbtest

SSH_USERNAME=jungnoh
SSH_PASSWORD=asdfasdf
SSH_HOST=localhost
SSH_PORT=5555
